"""
Streamlit frontend for AI Bioinformatics Assistant - Enhanced UI.
Optimized for performance and memory efficiency.
"""
import streamlit as st
import requests
import json
from typing import Optional, Dict, Any
import os
from dotenv import load_dotenv
import hashlib
from datetime import datetime

load_dotenv()

st.set_page_config(
    page_title="BioGenius - AI Bioinformatics Assistant",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        "Get help": "https://github.com/yourusername/bioinformatics-assistant",
        "Report a bug": "https://github.com/yourusername/bioinformatics-assistant/issues",
        "About": "AI-powered bioinformatics education and analysis platform"
    }
)

# Cache decorator for expensive operations
@st.cache_data(ttl=3600)
def cache_analysis_results(data_hash: str, analysis_data: Dict[str, Any]) -> Dict[str, Any]:
    """Cache analysis results for 1 hour."""
    return analysis_data

def get_data_hash(content: str) -> str:
    """Generate hash of content for caching."""
    return hashlib.md5(content.encode()).hexdigest()

def generate_chat_summary_report(chat_history: list) -> str:
    """Generate a formatted text report from chat history."""
    report = "=" * 70 + "\n"
    report += "BIOGENIUS AI - CHAT CONVERSATION SUMMARY REPORT\n"
    report += "=" * 70 + "\n"
    report += f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    report += f"Total Messages: {len(chat_history)}\n"
    report += f"Questions: {sum(1 for m in chat_history if m['role'] == 'user')}\n"
    report += f"Responses: {sum(1 for m in chat_history if m['role'] == 'assistant')}\n"
    report += "=" * 70 + "\n\n"

    for idx, msg in enumerate(chat_history, 1):
        if msg["role"] == "user":
            report += f"Q{(idx + 1) // 2}: {msg['content']}\n"
            report += "-" * 70 + "\n"
        else:
            report += f"A{idx // 2}: {msg['content']}\n"
            report += "=" * 70 + "\n\n"

    return report

def generate_markdown_report(chat_history: list, sequence_data: dict = None) -> str:
    """Generate a markdown formatted report."""
    report = "# BioGenius AI Analysis Report\n\n"
    report += f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

    # Summary statistics
    report += "## Session Summary\n\n"
    report += f"- **Total Messages:** {len(chat_history)}\n"
    report += f"- **Questions Asked:** {sum(1 for m in chat_history if m['role'] == 'user')}\n"
    report += f"- **AI Responses:** {sum(1 for m in chat_history if m['role'] == 'assistant')}\n"
    report += f"- **Total Characters:** {sum(len(m['content']) for m in chat_history):,}\n\n"

    # Sequence analysis section
    if sequence_data:
        report += "## Sequence Analysis\n\n"
        report += f"- **Total Sequences:** {sequence_data.get('total_sequences', 0)}\n"
        report += f"- **Total Length:** {sequence_data.get('total_length', 0):,} bp\n"
        report += f"- **Average Length:** {sequence_data.get('average_length', 0):,.0f} bp\n"
        report += f"- **Average GC Content:** {sequence_data.get('average_gc_content', 0):.2f}%\n\n"

    # Conversation details
    report += "## Conversation Details\n\n"
    q_count = 0
    for idx, msg in enumerate(chat_history):
        if msg["role"] == "user":
            q_count += 1
            report += f"### Question {q_count}\n\n"
            report += f"{msg['content']}\n\n"
        else:
            report += f"**Response:**\n\n"
            report += f"{msg['content']}\n\n"
            report += "---\n\n"

    report += f"---\n\n*Generated by BioGenius AI v2.0.0*\n"
    return report

def generate_sequence_annotation_report(sequence_data: dict, chat_history: list = None) -> str:
    """Generate a sequence annotation report."""
    report = "=" * 70 + "\n"
    report += "SEQUENCE ANNOTATION REPORT - BIOGENIUS AI\n"
    report += "=" * 70 + "\n"
    report += f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

    if not sequence_data:
        return report + "No sequence data available.\n"

    # Overall statistics
    report += "OVERALL STATISTICS\n"
    report += "-" * 70 + "\n"
    report += f"Total Sequences Analyzed: {sequence_data.get('total_sequences', 0)}\n"
    report += f"Total Length: {sequence_data.get('total_length', 0):,} bp\n"
    report += f"Average Length: {sequence_data.get('average_length', 0):,.0f} bp\n"
    report += f"Average GC Content: {sequence_data.get('average_gc_content', 0):.2f}%\n\n"

    # Individual sequences
    if sequence_data.get('sequences'):
        report += "DETAILED SEQUENCE ANALYSIS\n"
        report += "-" * 70 + "\n\n"

        for idx, seq in enumerate(sequence_data['sequences'][:20], 1):
            report += f"Sequence {idx}: {seq.get('header', 'Unknown')}\n"
            report += f"  Length: {seq.get('length', 0):,} bp\n"
            report += f"  GC Content: {seq.get('gc_content', 0):.2f}%\n"
            report += f"  AT Content: {seq.get('at_content', 0):.2f}%\n"
            report += f"  Nucleotide Composition:\n"
            report += f"    A: {seq.get('a_percent', 0):.2f}%\n"
            report += f"    T: {seq.get('t_percent', 0):.2f}%\n"
            report += f"    G: {seq.get('g_percent', 0):.2f}%\n"
            report += f"    C: {seq.get('c_percent', 0):.2f}%\n\n"

        if len(sequence_data['sequences']) > 20:
            report += f"... and {len(sequence_data['sequences']) - 20} more sequences\n\n"

    # AI insights if available
    if chat_history:
        report += "AI ANALYSIS INSIGHTS\n"
        report += "-" * 70 + "\n"
        for msg in chat_history:
            if msg["role"] == "assistant":
                report += f"{msg['content']}\n\n"
                break

    report += "=" * 70 + "\n"
    return report

BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

# Custom CSS for enhanced aesthetics
st.markdown("""
<style>
    :root {
        --primary-color: #2E86AB;
        --secondary-color: #A23B72;
        --success-color: #06A77D;
        --warning-color: #F18F01;
        --danger-color: #C73E1D;
        --light-bg: #F8F9FA;
        --dark-text: #1F2937;
    }

    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background: linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%);
    }

    /* Main title styling */
    h1 {
        color: #2E86AB;
        font-weight: 700;
        text-shadow: 0 2px 4px rgba(0,0,0,0.1);
        margin-bottom: 1rem;
    }

    h2 {
        color: #2E86AB;
        border-bottom: 3px solid #06A77D;
        padding-bottom: 0.5rem;
        margin-top: 1.5rem;
    }

    h3 {
        color: #A23B72;
        margin-top: 1rem;
    }

    /* Sidebar styling */
    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, #F3F4F6 0%, #E9ECEF 100%);
        padding: 2rem 1rem;
    }

    [data-testid="stSidebar"] h2 {
        color: #FFFFFF;
        background: linear-gradient(135deg, #2E86AB 0%, #1F5A7A 100%);
        border-bottom: 2px solid #06A77D;
        text-shadow: 0 1px 2px rgba(0,0,0,0.1);
        padding: 1rem;
        border-radius: 8px;
        margin: -1rem -1rem 1rem -1rem;
    }

    [data-testid="stSidebar"] h3 {
        color: #FFFFFF;
        background: linear-gradient(135deg, #2E86AB 0%, #1F5A7A 100%);
        padding: 0.75rem;
        border-radius: 6px;
        margin: 1rem -1rem 0.5rem -1rem;
        padding-left: 1rem;
        padding-right: 1rem;
    }

    [data-testid="stSidebar"] label {
        color: #374151;
        font-weight: 500;
    }

    /* Button styling */
    .stButton > button {
        background: linear-gradient(135deg, #2E86AB 0%, #1F5A7A 100%);
        color: white;
        border: none;
        border-radius: 8px;
        padding: 0.75rem 1.5rem;
        font-weight: 600;
        transition: all 0.3s ease;
        box-shadow: 0 4px 6px rgba(46, 134, 171, 0.2);
    }

    .stButton > button:hover {
        transform: translateY(-2px);
        box-shadow: 0 8px 12px rgba(46, 134, 171, 0.4);
        background: linear-gradient(135deg, #1F5A7A 0%, #2E86AB 100%);
    }

    /* Sidebar buttons - Black with white text */
    [data-testid="stSidebar"] .stButton > button {
        background: linear-gradient(135deg, #1A1A1A 0%, #000000 100%);
        color: #FFFFFF;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.4);
        border: 1px solid #333333;
    }

    [data-testid="stSidebar"] .stButton > button:hover {
        background: linear-gradient(135deg, #2D2D2D 0%, #1A1A1A 100%);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.6);
        transform: translateY(-2px);
    }

    [data-testid="stSidebar"] .stButton > button:active {
        transform: translateY(0);
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
    }

    /* Metric cards */
    .metric-card {
        background: white;
        padding: 1.5rem;
        border-radius: 12px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        border-left: 4px solid #2E86AB;
        transition: all 0.3s ease;
    }

    .metric-card:hover {
        box-shadow: 0 8px 16px rgba(0,0,0,0.15);
        transform: translateY(-4px);
    }

    /* Expander styling */
    .streamlit-expanderHeader {
        background: linear-gradient(90deg, #2E86AB 0%, #A23B72 100%);
        color: white;
        border-radius: 8px;
        padding: 1rem;
    }

    .streamlit-expanderHeader:hover {
        background: linear-gradient(90deg, #1F5A7A 0%, #8B2F5E 100%);
    }

    /* Input styling */
    input, textarea {
        border-radius: 8px !important;
        border: 2px solid #E9ECEF !important;
        transition: all 0.3s ease;
    }

    input:focus, textarea:focus {
        border: 2px solid #2E86AB !important;
        box-shadow: 0 0 0 3px rgba(46, 134, 171, 0.1) !important;
    }

    /* Chat messages */
    .chat-message {
        padding: 1.5rem;
        border-radius: 12px;
        margin-bottom: 1rem;
        box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    }

    .chat-message.user {
        background: linear-gradient(135deg, #2E86AB 0%, #1F5A7A 100%);
        color: white;
        margin-left: 2rem;
    }

    .chat-message.assistant {
        background: linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%);
        border-left: 4px solid #06A77D;
        margin-right: 2rem;
    }

    /* Alert styling */
    .stAlert {
        border-radius: 8px;
        padding: 1rem;
        margin-bottom: 1rem;
    }

    .stSuccess {
        background-color: #D4EDDA;
        color: #155724;
        border: 1px solid #C3E6CB;
        border-radius: 8px;
    }

    .stError {
        background-color: #F8D7DA;
        color: #721C24;
        border: 1px solid #F5C6CB;
        border-radius: 8px;
    }

    .stWarning {
        background-color: #FFF3CD;
        color: #856404;
        border: 1px solid #FFEEBA;
        border-radius: 8px;
    }

    .stInfo {
        background-color: #D1ECF1;
        color: #0C5460;
        border: 1px solid #BEE5EB;
        border-radius: 8px;
    }

    /* Divider */
    hr {
        margin: 2rem 0;
        border: none;
        height: 2px;
        background: linear-gradient(90deg, transparent, #2E86AB, transparent);
    }

    /* Code blocks */
    code {
        background-color: #F1F5F9;
        padding: 0.25rem 0.5rem;
        border-radius: 4px;
        color: #C73E1D;
        font-weight: 600;
    }

    /* Scrollbar */
    ::-webkit-scrollbar {
        width: 8px;
    }

    ::-webkit-scrollbar-track {
        background: #F1F5F9;
    }

    ::-webkit-scrollbar-thumb {
        background: #2E86AB;
        border-radius: 4px;
    }

    ::-webkit-scrollbar-thumb:hover {
        background: #1F5A7A;
    }
</style>
""", unsafe_allow_html=True)

st.markdown("""
<div style="text-align: center; margin-bottom: 2rem;">
    <h1 style="font-size: 3rem; margin-bottom: 0.5rem;">🧬 BioGenius</h1>
    <p style="font-size: 1.1rem; color: #666; margin: 0;">
        AI-Powered Bioinformatics Education & Sequence Analysis Platform
    </p>
</div>
""", unsafe_allow_html=True)

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "sequence_context" not in st.session_state:
    st.session_state.sequence_context = None

if "uploaded_sequences" not in st.session_state:
    st.session_state.uploaded_sequences = []

if "show_analysis" not in st.session_state:
    st.session_state.show_analysis = False

if "session_start_time" not in st.session_state:
    st.session_state.session_start_time = datetime.now()

if "show_chat_history_panel" not in st.session_state:
    st.session_state.show_chat_history_panel = False

with st.sidebar:
    st.markdown("<h2>🔧 Settings & Upload</h2>", unsafe_allow_html=True)

    st.markdown("""
    <div style="background: linear-gradient(135deg, #2E86AB 0%, #1F5A7A 100%); padding: 1rem; border-radius: 8px; margin-bottom: 1.5rem;">
        <p style="color: #FFFFFF; margin: 0; font-size: 0.9rem;">
            Upload biological sequence files and analyze them with AI-powered insights
        </p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("<h3>📤 Sequence Files</h3>", unsafe_allow_html=True)
    uploaded_files = st.file_uploader(
        "Upload FASTA/FASTQ files",
        type=["fasta", "fastq", "fa", "fna", "fq", "txt"],
        accept_multiple_files=True,
        help="Supported: FASTA (.fasta, .fa, .fna), FASTQ (.fastq, .fq), Text (.txt)"
    )

    st.markdown("<h3 style='color: #E8F4F8;'>⚙️ Analysis Options</h3>", unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    with col1:
        detect_orfs = st.checkbox(
            "Detect ORFs",
            value=False,
            help="Find Open Reading Frames in sequences"
        )
    with col2:
        st.info("💡 ORF Detection analyzes protein-coding regions", icon="ℹ️")

    col_analyze, col_clear = st.columns(2)
    with col_analyze:
        if st.button("📊 Analyze", use_container_width=True):
            if uploaded_files:
                st.session_state.uploaded_sequences = []
                st.session_state.show_analysis = True

                for uploaded_file in uploaded_files:
                    file_content = uploaded_file.read().decode("utf-8")
                    file_extension = uploaded_file.name.split('.')[-1].lower()

                    with st.spinner(f"🔬 Analyzing {uploaded_file.name}..."):
                        try:
                            response = requests.post(
                                f"{BACKEND_URL}/analyze",
                                json={
                                    "content": file_content,
                                    "file_format": file_extension,
                                    "detect_orfs": detect_orfs
                                },
                                timeout=30
                            )
                            response.raise_for_status()
                            result = response.json()

                            if result["success"]:
                                st.session_state.sequence_context = result.get("analysis")
                                st.session_state.uploaded_sequences.append({
                                    "filename": uploaded_file.name,
                                    "analysis": result.get("analysis"),
                                    "orfs": result.get("orfs")
                                })
                                st.success(f"✅ {uploaded_file.name} analyzed!")
                            else:
                                st.error(f"Error: {result.get('error')}")

                        except requests.exceptions.ConnectionError:
                            st.error("❌ Cannot connect to backend (port 8000)")
                        except Exception as e:
                            st.error(f"Error: {str(e)}")
            else:
                st.warning("⚠️ Upload files first")

    with col_clear:
        if st.button("🗑️ Clear", use_container_width=True):
            st.session_state.chat_history = []
            st.session_state.sequence_context = None
            st.session_state.uploaded_sequences = []
            st.session_state.show_analysis = False
            st.rerun()

    st.markdown("<hr style='margin: 2rem 0;'>", unsafe_allow_html=True)

    with st.expander("📚 Learning Resources", expanded=False):
        st.markdown("""
        <div style="padding: 1rem;">
            <h4 style="color: #E8F4F8; margin-top: 0;">FASTA Format</h4>
            <code style="background: rgba(0,0,0,0.3); color: #FFD700; padding: 0.5rem; border-radius: 4px; display: block;">
>sequence_id description
ATGCGATCGATCGATCG
            </code>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("""
        <div style="padding: 1rem;">
            <h4 style="color: #E8F4F8; margin-top: 0;">FASTQ Format</h4>
            <code style="background: rgba(0,0,0,0.3); color: #FFD700; padding: 0.5rem; border-radius: 4px; display: block;">
@sequence_id
ATGCGATCGATCGATCG
+
IIIIIIIIIIIIIIII
            </code>
        </div>
        """, unsafe_allow_html=True)

    with st.expander("💡 Popular Questions", expanded=False):
        questions = [
            "What is GC content and why does it matter?",
            "How do I interpret open reading frames?",
            "Explain genome assembly",
            "What's the difference between DNA and RNA?",
            "How does CRISPR gene editing work?",
            "What is next-generation sequencing?",
            "Analyze my uploaded sequences"
        ]
        for i, q in enumerate(questions, 1):
            st.markdown(f"<p style='color: #E8F4F8; margin: 0.5rem 0;'>{i}. {q}</p>", unsafe_allow_html=True)

main_col = st.container()

with main_col:
    if st.session_state.uploaded_sequences and st.session_state.show_analysis:
        st.markdown("""
        <div style='margin: 2rem 0 3rem 0;'>
            <h2 style='margin: 0 0 1rem 0;'>📊 Analysis Results</h2>
            <p style='color: #666; margin: 0;'>Comprehensive sequence analysis from your uploaded files</p>
        </div>
        """, unsafe_allow_html=True)

        for seq_data in st.session_state.uploaded_sequences:
            with st.container():
                st.markdown(f"""
                <div style='background: white; padding: 1.5rem; border-radius: 12px;
                            margin-bottom: 2rem; box-shadow: 0 2px 8px rgba(0,0,0,0.1);
                            border-left: 5px solid #2E86AB;'>
                    <h3 style='margin: 0 0 1.5rem 0; color: #2E86AB;'>📄 {seq_data['filename']}</h3>
                """, unsafe_allow_html=True)

                if seq_data.get("analysis"):
                    analysis = seq_data["analysis"]

                    # Metrics in styled cards
                    col1, col2, col3, col4 = st.columns(4, gap="medium")

                    metrics = [
                        ("Sequences", f"{analysis.get('total_sequences', 0)}", "🔢"),
                        ("Total Length", f"{analysis.get('total_length', 0):,} bp", "📏"),
                        ("Avg Length", f"{analysis.get('average_length', 0):,.0f} bp", "📊"),
                        ("Avg GC%", f"{analysis.get('average_gc_content', 0):.1f}%", "⚗️")
                    ]

                    for col, (label, value, emoji) in zip([col1, col2, col3, col4], metrics):
                        with col:
                            st.markdown(f"""
                            <div style='background: linear-gradient(135deg, #F0F4F8 0%, #E0E8F0 100%);
                                        padding: 1.5rem; border-radius: 10px; text-align: center;'>
                                <p style='margin: 0; font-size: 2rem;'>{emoji}</p>
                                <p style='margin: 0.5rem 0 0 0; color: #666; font-size: 0.9rem;'>{label}</p>
                                <p style='margin: 0.5rem 0 0 0; color: #2E86AB; font-size: 1.3rem; font-weight: 700;'>{value}</p>
                            </div>
                            """, unsafe_allow_html=True)

                    # Detailed sequence information
                    if analysis.get("sequences"):
                        with st.expander("📋 Detailed Sequence Information", expanded=True):
                            for seq_info in analysis["sequences"]:
                                st.markdown(f"""
                                <div style='background: #F8F9FA; padding: 1rem; border-radius: 8px; margin-bottom: 1rem;
                                            border-left: 3px solid #06A77D;'>
                                    <h4 style='margin: 0 0 0.5rem 0; color: #2E86AB;'>{seq_info['header']}</h4>
                                    <div style='display: grid; grid-template-columns: 1fr 1fr 1fr 1fr; gap: 1rem;'>
                                        <div>
                                            <small style='color: #666;'>Length</small>
                                            <p style='margin: 0.25rem 0 0 0; font-weight: 600;'>{seq_info['length']} bp</p>
                                        </div>
                                        <div>
                                            <small style='color: #666;'>GC Content</small>
                                            <p style='margin: 0.25rem 0 0 0; font-weight: 600;'>{seq_info['gc_content']:.1f}%</p>
                                        </div>
                                        <div>
                                            <small style='color: #666;'>AT Content</small>
                                            <p style='margin: 0.25rem 0 0 0; font-weight: 600;'>{seq_info['at_content']:.1f}%</p>
                                        </div>
                                        <div>
                                            <small style='color: #666;'>Composition</small>
                                            <p style='margin: 0.25rem 0 0 0; font-weight: 600;'>A:{seq_info['a_percent']:.1f}% T:{seq_info['t_percent']:.1f}%</p>
                                        </div>
                                    </div>
                                </div>
                                """, unsafe_allow_html=True)

                # ORF Detection Results
                if seq_data.get("orfs"):
                    with st.expander("🧬 Open Reading Frames (ORFs)", expanded=False):
                        orf_count = len(seq_data['orfs'])
                        st.markdown(f"""
                        <div style='background: linear-gradient(135deg, #E8F5E9 0%, #C8E6C9 100%);
                                    padding: 1rem; border-radius: 8px; margin-bottom: 1rem;'>
                            <p style='margin: 0; color: #2E7D32; font-weight: 600;'>
                                ✅ Found <strong>{orf_count}</strong> Open Reading Frames
                            </p>
                        </div>
                        """, unsafe_allow_html=True)

                        for i, orf in enumerate(seq_data["orfs"][:15], 1):
                            st.markdown(f"""
                            <div style='background: #F5F5F5; padding: 0.75rem; border-radius: 6px;
                                        margin-bottom: 0.5rem; border-left: 3px solid #FF9800;'>
                                <small><strong>ORF {i}</strong> | Position: {orf['start']}-{orf['end']} |
                                Length: {orf['length']} bp</small>
                            </div>
                            """, unsafe_allow_html=True)

                        if orf_count > 15:
                            st.info(f"Showing 15 of {orf_count} ORFs")

                st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("<hr style='margin: 3rem 0;'>", unsafe_allow_html=True)

    # Chat section
    st.markdown("""
    <div style='margin: 2rem 0 1rem 0;'>
        <h2 style='margin: 0 0 0.5rem 0;'>💬 AI Bioinformatics Assistant</h2>
        <p style='color: #666; margin: 0;'>Ask questions about bioinformatics or your sequences</p>
    </div>
    """, unsafe_allow_html=True)

    # Chat history display with enhanced features
    chat_container = st.container()

    with chat_container:
        # Chat history summary/stats
        if st.session_state.chat_history:
            col1, col2, col3, col4 = st.columns(4)
            with col1:
                user_messages = sum(1 for m in st.session_state.chat_history if m["role"] == "user")
                st.metric("Your Questions", user_messages)
            with col2:
                ai_messages = sum(1 for m in st.session_state.chat_history if m["role"] == "assistant")
                st.metric("AI Responses", ai_messages)
            with col3:
                total_chars = sum(len(m["content"]) for m in st.session_state.chat_history)
                st.metric("Total Characters", f"{total_chars:,}")
            with col4:
                st.metric("Conversation Turns", len(st.session_state.chat_history) // 2)

            st.markdown("<hr style='margin: 1rem 0;'>", unsafe_allow_html=True)

        # Display chat messages with timestamps
        if st.session_state.chat_history:
            st.markdown("""
            <div style='max-height: 600px; overflow-y: auto; padding: 1rem 0;'>
            """, unsafe_allow_html=True)

            for idx, message in enumerate(st.session_state.chat_history):
                if message["role"] == "user":
                    st.markdown(f"""
                    <div style='background: linear-gradient(135deg, #2E86AB 0%, #1F5A7A 100%);
                                color: white; padding: 1.5rem; border-radius: 12px; margin-bottom: 1rem;
                                margin-left: 2rem; box-shadow: 0 2px 8px rgba(46, 134, 171, 0.2);'>
                        <div style='display: flex; justify-content: space-between; align-items: center;'>
                            <small style='opacity: 0.8;'>👤 You</small>
                            <small style='opacity: 0.6; font-size: 0.75rem;'>Message {idx + 1}</small>
                        </div>
                        <p style='margin: 0.75rem 0 0 0; line-height: 1.5;'>{message["content"]}</p>
                    </div>
                    """, unsafe_allow_html=True)
                else:
                    st.markdown(f"""
                    <div style='background: linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%);
                                color: #1F2937; padding: 1.5rem; border-radius: 12px; margin-bottom: 1rem;
                                margin-right: 2rem; border-left: 4px solid #06A77D;
                                box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);'>
                        <div style='display: flex; justify-content: space-between; align-items: center;'>
                            <small style='color: #06A77D; font-weight: 600;'>🧬 BioGenius AI</small>
                            <small style='opacity: 0.6; font-size: 0.75rem;'>Response {idx + 1}</small>
                        </div>
                        <p style='margin: 0.75rem 0 0 0; line-height: 1.6;'>{message["content"]}</p>
                    </div>
                    """, unsafe_allow_html=True)

            st.markdown("</div>", unsafe_allow_html=True)

    # Chat input
    st.markdown("""
    <div style='margin-top: 2rem; padding-top: 2rem; border-top: 2px solid #E9ECEF;'>
    """, unsafe_allow_html=True)

    prompt = st.chat_input("💬 Ask me anything about bioinformatics...", key="chat_input")

    if prompt:
        st.session_state.chat_history.append({
            "role": "user",
            "content": prompt
        })

        # Display user message immediately
        st.markdown(f"""
        <div style='background: linear-gradient(135deg, #2E86AB 0%, #1F5A7A 100%);
                    color: white; padding: 1.5rem; border-radius: 12px; margin-bottom: 1rem;
                    margin-left: 2rem; box-shadow: 0 2px 8px rgba(46, 134, 171, 0.2);'>
            <small style='opacity: 0.8;'>You</small>
            <p style='margin: 0.5rem 0 0 0; line-height: 1.5;'>{prompt}</p>
        </div>
        """, unsafe_allow_html=True)

        with st.spinner("🤔 AI is thinking..."):
            try:
                chat_payload = {
                    "query": prompt,
                    "chat_history": st.session_state.chat_history[:-1],
                }

                if st.session_state.sequence_context:
                    chat_payload["sequence_context"] = st.session_state.sequence_context

                response = requests.post(
                    f"{BACKEND_URL}/chat",
                    json=chat_payload,
                    timeout=30
                )
                response.raise_for_status()
                result = response.json()

                if not result.get("error"):
                    assistant_response = result.get("response", "No response received")
                    st.session_state.chat_history.append({
                        "role": "assistant",
                        "content": assistant_response
                    })

                    st.markdown(f"""
                    <div style='background: linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%);
                                color: #1F2937; padding: 1.5rem; border-radius: 12px; margin-bottom: 1rem;
                                margin-right: 2rem; border-left: 4px solid #06A77D;
                                box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);'>
                        <small style='color: #06A77D; font-weight: 600;'>🧬 BioGenius AI</small>
                        <p style='margin: 0.5rem 0 0 0; line-height: 1.6;'>{assistant_response}</p>
                    </div>
                    """, unsafe_allow_html=True)

                    st.rerun()
                else:
                    error_msg = result.get("message", "Unknown error")
                    st.error(f"❌ {error_msg}")

            except requests.exceptions.ConnectionError:
                st.error("❌ Cannot connect to backend. Make sure FastAPI is running: `python backend/main.py`")
            except Exception as e:
                st.error(f"❌ Error: {str(e)}")

    st.markdown("</div>", unsafe_allow_html=True)

st.markdown("<hr style='margin: 3rem 0;'>", unsafe_allow_html=True)

# Export and utilities section with enhanced chat management
st.markdown("""
<div style='background: linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%);
            padding: 2rem; border-radius: 12px; margin-bottom: 2rem;'>
    <h3 style='color: #2E86AB; margin-top: 0;'>📥 Chat History & Export</h3>
""", unsafe_allow_html=True)

# Chat history management
if st.session_state.chat_history:
    st.markdown("""
    <div style='background: white; padding: 1rem; border-radius: 8px; margin-bottom: 1.5rem;'>
        <h4 style='color: #2E86AB; margin-top: 0;'>📊 Conversation Summary</h4>
    </div>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        # Copy chat history
        if st.button("📋 Copy Chat to Clipboard", use_container_width=True, key="copy_chat"):
            chat_text = "=== BioGenius Chat History ===\n\n"
            for idx, msg in enumerate(st.session_state.chat_history, 1):
                role = "👤 YOU" if msg["role"] == "user" else "🧬 BIOGENIUS AI"
                chat_text += f"{role} (Message {idx}):\n{msg['content']}\n\n"
                chat_text += "---\n\n"
            st.code(chat_text, language="text")

    with col2:
        # Export full results
        if st.button("📥 View Full History", use_container_width=True, key="view_full_history"):
            with st.expander("💬 Complete Chat History", expanded=True):
                for idx, msg in enumerate(st.session_state.chat_history, 1):
                    if msg["role"] == "user":
                        st.markdown(f"**👤 You (Message {idx}):**")
                    else:
                        st.markdown(f"**🧬 BioGenius AI (Response {idx}):**")
                    st.markdown(f"> {msg['content']}")
                    st.divider()

st.markdown("<hr style='margin: 1.5rem 0;'>", unsafe_allow_html=True)

# Report generation section
if st.session_state.chat_history or st.session_state.uploaded_sequences:
    st.markdown("""
    <div style='background: linear-gradient(135deg, #E8F5E9 0%, #C8E6C9 100%);
                padding: 1.5rem; border-radius: 12px; margin-bottom: 1.5rem;
                border-left: 4px solid #06A77D;'>
        <h4 style='color: #2E7D32; margin-top: 0;'>📄 Generate Reports</h4>
        <p style='color: #558B2F; margin-bottom: 1rem;'>Download comprehensive analysis reports in multiple formats</p>
    </div>
    """, unsafe_allow_html=True)

    report_col1, report_col2, report_col3 = st.columns(3, gap="medium")

    with report_col1:
        if st.button("📋 Chat Summary Report", use_container_width=True, key="report_chat_summary"):
            if st.session_state.chat_history:
                report_text = generate_chat_summary_report(st.session_state.chat_history)
                st.download_button(
                    label="📥 Download TXT Report",
                    data=report_text,
                    file_name=f"chat_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
                    mime="text/plain",
                    key="download_chat_summary"
                )
            else:
                st.warning("No chat history to generate report")

    with report_col2:
        if st.button("📊 Sequence Annotation Report", use_container_width=True, key="report_sequence"):
            if st.session_state.uploaded_sequences and st.session_state.sequence_context:
                report_text = generate_sequence_annotation_report(
                    st.session_state.sequence_context,
                    st.session_state.chat_history
                )
                st.download_button(
                    label="📥 Download TXT Report",
                    data=report_text,
                    file_name=f"sequence_annotation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
                    mime="text/plain",
                    key="download_sequence_report"
                )
            else:
                st.warning("Please analyze sequences first")

    with report_col3:
        if st.button("📑 Full Analysis Report (MD)", use_container_width=True, key="report_full"):
            if st.session_state.chat_history:
                report_md = generate_markdown_report(
                    st.session_state.chat_history,
                    st.session_state.sequence_context
                )
                st.download_button(
                    label="📥 Download Markdown",
                    data=report_md,
                    file_name=f"analysis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md",
                    mime="text/markdown",
                    key="download_full_report"
                )
            else:
                st.warning("No data to generate report")

st.markdown("<hr style='margin: 1.5rem 0;'>", unsafe_allow_html=True)

# Download and clear options
col1, col2, col3, col4 = st.columns(4, gap="medium")

with col1:
    if st.session_state.chat_history or st.session_state.uploaded_sequences:
        export_data = {
            "session_summary": {
                "total_messages": len(st.session_state.chat_history),
                "user_questions": sum(1 for m in st.session_state.chat_history if m["role"] == "user"),
                "ai_responses": sum(1 for m in st.session_state.chat_history if m["role"] == "assistant"),
                "exported_at": datetime.now().isoformat(),
                "version": "BioGenius v2.0.0"
            },
            "sequences": st.session_state.uploaded_sequences,
            "chat_history": st.session_state.chat_history
        }
        st.download_button(
            label="💾 Download JSON",
            data=json.dumps(export_data, indent=2),
            file_name=f"bioinformatics_session_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
            mime="application/json",
            use_container_width=True,
            key="download_json"
        )
    else:
        st.button("💾 Download JSON", use_container_width=True, disabled=True, key="download_disabled")

with col2:
    if st.session_state.chat_history:
        # Export as text file
        chat_text = "=== BioGenius Chat History ===\n"
        chat_text += f"Export Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        chat_text += f"Total Messages: {len(st.session_state.chat_history)}\n\n"
        chat_text += "=" * 50 + "\n\n"

        for idx, msg in enumerate(st.session_state.chat_history, 1):
            role = "YOU" if msg["role"] == "user" else "BIOGENIUS AI"
            chat_text += f"[{idx}] {role}:\n{msg['content']}\n\n"

        st.download_button(
            label="📄 Download TXT",
            data=chat_text,
            file_name=f"chat_history_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain",
            use_container_width=True,
            key="download_txt"
        )
    else:
        st.button("📄 Download TXT", use_container_width=True, disabled=True, key="download_txt_disabled")

with col3:
    if st.button("🗑️ Clear Chat", use_container_width=True, key="clear_chat"):
        st.session_state.chat_history = []
        st.rerun()

with col4:
    if st.button("🔄 New Session", use_container_width=True, key="new_session"):
        st.session_state.chat_history = []
        st.session_state.sequence_context = None
        st.session_state.uploaded_sequences = []
        st.session_state.show_analysis = False
        st.rerun()

st.markdown("</div>", unsafe_allow_html=True)

# Footer
st.markdown("""
<div style='text-align: center; padding: 2rem 0; border-top: 2px solid #E9ECEF; margin-top: 3rem;'>
    <p style='color: #666; margin: 0.5rem 0;'>
        🧬 <strong>BioGenius</strong> - AI-Powered Bioinformatics Education Platform
    </p>
    <p style='color: #999; margin: 0.5rem 0; font-size: 0.9rem;'>
        v1.0.0 | Built with Streamlit, FastAPI & OpenRouter API
    </p>
    <div style='margin-top: 1.5rem; padding: 1.5rem; background: linear-gradient(135deg, #E8F4F8 0%, #F0E8F8 100%);
                border-radius: 8px;'>
        <p style='margin: 0; color: #2E86AB; font-weight: 600;'>✨ Tips for Best Results</p>
        <ul style='margin: 0.5rem 0 0 0; color: #666; font-size: 0.9rem; text-align: left; display: inline-block;'>
            <li>Upload well-formatted FASTA/FASTQ files</li>
            <li>Use descriptive sequence headers for better analysis</li>
            <li>Ask specific questions about your sequences</li>
            <li>Enable ORF detection for protein-coding analysis</li>
        </ul>
    </div>
</div>
""", unsafe_allow_html=True)

# Empty state message
if not st.session_state.chat_history and not st.session_state.uploaded_sequences:
    st.markdown("""
    <div style='text-align: center; padding: 3rem 2rem;'>
        <p style='font-size: 3rem; margin: 0;'>🧬</p>
        <h2 style='color: #2E86AB; margin: 1rem 0;'>Welcome to BioGenius</h2>
        <p style='color: #666; font-size: 1.05rem; margin: 0 0 1.5rem 0;'>
            Your AI-powered bioinformatics companion
        </p>
        <div style='background: linear-gradient(135deg, #E8F4F8 0%, #F0E8F8 100%);
                    padding: 1.5rem; border-radius: 8px; max-width: 500px; margin: 0 auto;'>
            <p style='margin: 0.5rem 0; color: #2E86AB; font-weight: 600;'>Get Started:</p>
            <ol style='text-align: left; color: #666; margin: 0.5rem 0 0 0;'>
                <li>Upload a FASTA or FASTQ file in the sidebar</li>
                <li>Click "Analyze" to examine your sequences</li>
                <li>Ask the AI questions about your data</li>
                <li>Export your results when done</li>
            </ol>
        </div>
    </div>
    """, unsafe_allow_html=True)
